languageCode = "tr"
languageName = "Türkçe"
weight = 1
title = "Paylaşım Merkezi"

[params]
  displayName = "TR"
  isoCode = "tr"
  rtl = false
  dateFormat = "2 Ocak 2006"
  description = "Gerçek geziler, gerçek hatalar, gerçek deneyimler."
  author.name = "Share-Hub-EU"
