languageCode = "de"
languageName = "Deutsch"
weight = 3
title = "Teilen-Zentrum"

[params]
  displayName = "DE"
  isoCode = "de"
  logo = "/img/sharehubeu-logo.png"
  homepageImage = "/img/sharehubeu-hero.png"
  showLogo = true
  showName = true
  layout = "hero"
  showTitle = true
  rtl = false
  dateFormat = "2. Januar 2006"
  description = "Echte Reisen, echte Fehler, echte Erfahrungen."
  author.name = "Share-Hub-EU"
