languageCode = "tr"
languageName = "Türkçe"
weight = 1
title = "Paylaşım Merkezi"

[params]
  logo = "img/sharehubeu-logo.png"
  showLogo = true
  showName = true
  layout = "fixed"
  homepageImage = "img/sharehubeu-hero.png"
  showTitle = true
  displayName = "TR"
  isoCode = "tr"
  rtl = false
  dateFormat = "2 Ocak 2006"
  description = "Gerçek geziler, gerçek hatalar, gerçek deneyimler."
  author.name = "Share-Hub-EU"
