[[main]]
  name = "Startseite"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Deutschland"
  pageRef = "almanya"
  weight = 2

[[main]]
  name = "Reisen"
  pageRef = "seyahat"
  weight = 3

[[main]]
  name = "Über mich"
  pageRef = "hakkimda"
  weight = 4

[[main]]
  name = "Kontakt"
  pageRef = "iletisim"
  weight = 5
